In [5]:
import pandas as pd

df = pd.read_csv('sales_data.csv')

## Задание 1

### Первые 5 строк

In [7]:
df.head()

,TransactionID,Date,CustomerID,ProductCategory,SalesAmount,Discount,Quantity,Region
0,TX0001,2026-03-04,C005,Clothing,419.09,0.01,1,North
1,TX0002,2026-03-24,C005,Books,365.28,0.16,2,East
2,TX0003,2026-03-18,C005,Home,157.54,0.22,1,East
3,TX0004,2026-03-09,C002,Electronics,100.72,0.13,3,West
4,TX0005,2026-03-25,C005,Electronics,493.58,0.29,5,East

In [9]:
### Последние 5 строк

In [10]:
df.tail()

,TransactionID,Date,CustomerID,ProductCategory,SalesAmount,Discount,Quantity,Region
145,TX0146,2026-03-18,C004,Books,234.86,0.06,2,East
146,TX0147,2026-03-09,C002,Electronics,71.77,0.09,1,South
147,TX0148,2026-01-17,C001,Books,79.66,0.26,4,South
148,TX0149,2026-03-03,C005,Electronics,412.10,0.30,2,North
149,TX0150,2026-02-22,C002,Electronics,276.88,0.13,2,East

## Задание 2

Определить:
* общее количество строк и столбцов;
* названия всех столбцов;
* тип данных каждого столбца.

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    150 non-null    str
 1   Date             150 non-null    str
 2   CustomerID       150 non-null    str
 3   ProductCategory  150 non-null    str
 4   SalesAmount      147 non-null    float64
 5   Discount         150 non-null    float64
 6   Quantity         150 non-null    int64
 7   Region           150 non-null    str
dtypes: float64(2), int64(1), str(5)
memory usage: 9.5 KB

In [25]:
print(f"Количество строк и столбцов: {df.shape}\n")
print(f"Названия всех столбцов:\n{", ".join([i for i in df.columns])}\n")
print(f"Тип данных для каждого столбца:\n{df.dtypes}\n")

Количество строк и столбцов: (150, 8)

Названия всех столбцов:
TransactionID, Date, CustomerID, ProductCategory, SalesAmount, Discount, Quantity, Region

Тип данных для каждого столбца:
TransactionID          str
Date                   str
CustomerID             str
ProductCategory        str
SalesAmount        float64
Discount           float64
Quantity             int64
Region                 str
dtype: object

## Задание 3

Найдите, в каких столбцах есть пропуски и сколько их.

In [26]:
df.isnull().sum() # в каких столбцах есть пропуски и сколько их

TransactionID      0
Date               0
CustomerID         0
ProductCategory    0
SalesAmount        3
Discount           0
Quantity           0
Region             0
dtype: int64

## Задание 4

Постройте описательную статистику для числовых столбцов

In [27]:
df[['SalesAmount','Discount','Quantity']].describe()

       SalesAmount    Discount    Quantity
count   147.000000  150.000000  150.000000
mean    232.433946    0.149667    2.666667
std     141.546160    0.088115    1.463959
min      11.520000    0.000000    1.000000
25%     100.270000    0.080000    1.000000
50%     217.120000    0.150000    2.000000
75%     365.735000    0.220000    4.000000
max     497.080000    0.300000    5.000000

## Задание 5
Выберите все транзакции, у которых сумма продаж (SalesAmount) больше 200 и категория товара 'Electronic

In [28]:
df[(df['SalesAmount'] > 200) & (df['ProductCategory'] == 'Electronics')]

,TransactionID,Date,CustomerID,ProductCategory,SalesAmount,Discount,Quantity,Region
4,TX0005,2026-03-25,C005,Electronics,493.58,0.29,5,East
17,TX0018,2026-01-18,C004,Electronics,320.19,0.05,4,South
47,TX0048,2026-03-21,C003,Electronics,441.94,0.08,5,East
48,TX0049,2026-02-20,C003,Electronics,410.30,0.26,5,South
50,TX0051,2026-01-16,C004,Electronics,436.37,0.12,3,East
55,TX0056,2026-01-10,C005,Electronics,371.43,0.12,5,North
57,TX0058,2026-03-03,C005,Electronics,289.34,0.11,3,East
59,TX0060,2026-03-01,C005,Electronics,238.09,0.06,5,East
62,TX0063,2026-03-28,C001,Electronics,497.08,0.03,1,North
67,TX0068,2026-02-08,C001,Electronics,221.75,0.16,1,North
72,TX0073,2026-03-06,C003,Electronics,453.24,0.03,2,South
92,TX0093,2026-03-17,C003,Electronics,223.51,0.00,2,South
96,TX0097,2026-03-30,C005,Electronics,222.07,0.04,1,West
97,TX0098,2026-01-08,C003,Electronics,367.64,0.01,1,West
103,TX0104,2026-03-27,C005,Electronics,281.69,0.07,2,East
106,TX0107,2026-02-07,C005,Electronics,466.48,0.10,3,West
108,TX0109,2026-03-17,C004,Electronics,373.30,0.06,3,West
126,TX0127,2026-03-16,C005,Electronics,210.70,0.21,5,West
127,TX0128,2026-01-23,C002,Electronics,324.65,0.19,3,South
133,TX0134,2026-01-25,C002,Electronics,245.93,0.00,2,West
138,TX0139,2026-01-14,C005,Electronics,432.72,0.02,2,South
148,TX0149,2026-03-03,C005,Electronics,412.10,0.30,2,North
149,TX0150,2026-02-22,C002,Electronics,276.88,0.13,2,East